# workbox.node.yaml
id: workbox
name: "Lenovo Yoga 9i"
address:
  local: "192.168.12.136"
capabilities:
  - Libvirt + KVM 
  - Container Runtimes
  - Ollama Runtimes

details:
  software:
    os: "Debian 13"
    kernel: ""
 
  hardware:
    network:
      - type: ethernet
        interface: <TODO>
        vendor: <TODO>
        model: <TODO>
        driver: <TODO>
        driver_version: <TODO>
        mac_address: <TODO>
        link_status: <TODO>
        capabilities:
          - <TODO>
          - <TODO>
          - <TODO>

      - type: wireless
        interface: wlp0s20f3
        vendor: Intel Corporation
        model: "Meteor Lake PCH CNVi WiFi"
        pci_id: "0000:00:14.3"
        driver: iwlwifi
        driver_version: "6.16.10-arch1-1"
        firmware: "89.2e78fa67.0 ma-b0-gf-a0-89.uc"
        mac_address: bc:38:98:a5:40:c4
        ip_address: 192.168.12.136
        link_status: enabled
        capabilities:
          - 802.11ax
          - 2.4GHz
          - 5GHz
          - PCIe
          - bus_master
          - msi
          - msix

    processor:
      name: Intel Core Ultra 7 155H
      family: Meteor Lake
      release_year: 2023
      architecture: x86_64
      process_node: Intel 4 (7nm class)
      cores:
        total: 16
        layout:
          performance_cores: 6
          efficient_cores: 8
          low_power_efficient_cores: 2
      threads: 22
      base_clock_ghz: 3.8
      boost_clock_ghz: 4.8
      tdp_watts:
        min: 28
        max: 115
      graphics:
        type: Intel Arc
        architecture: Xe-LPG
        cores: 8
      ai_accelerator:
        present: true
        type: Intel NPU
      virtualization:
        vt_x: true
        vt_d: true
      cache:
        l1: "544 KiB (data), 896 KiB (instruction)"
        l2: "18 MiB total"
        l3: "24 MiB shared"
      features:
        - Hyper-Threading
        - AVX2
        - AVX-VNNI
        - FMA
        - AES-NI
        - SHA
        - VT-x
        - VT-d
        - Turbo Boost
        - Integrated AI NPU
        - Integrated Arc GPU
      mitigation_status:
        meltdown: Not affected
        spectre_v1: Mitigated
        spectre_v2: Mitigated
        retbleed: Not affected
        mds: Not affected
        l1tf: Not affected

    graphics:
      name: "Intel Arc Graphics"
      vendor: Intel Corporation
      product: Meteor Lake-P
      driver: xe
      bus_info: pci@0000:00:02.0
      type: integrated
      resolution: "2880x1800"
      depth: 32
      capabilities:
        - PCIe
        - msi
        - bus_master
        - vga_controller

    memory:
      type: LPDDR5
      size: 16
      manufacturer: Micron Technology
      part_number: MT62F1G32D2DS-026
      speed_mt_s: 7467
      error_correction: None
      configuration:
        modules: 8
        configured_speed_mt_s: 7467
      architecture: 64-bit bus (LPDDR5)
    
    storage:
      type: NVMe SSD
      model: SAMSUNG MZAL81T0HDLB-00BL2
      product_name: PM9C1a
      vendor: Samsung Electronics Co Ltd
      interface: PCIe 4.0 x4 (NVMe 1.4)
      capacity_gib: 953
      capacity_gb: 1024
      bus_info: pci@0000:01:00.0
      logical_device: /dev/nvme0n1
      serial: S77LNF0X463530
      firmware_version: 6L1QKXD7
      form_factor: M.2 2280
      logical_sector_size: 512
      sector_size: 512
      partition_table: GPT
      guid: b4bfac61-0a72-4d49-b500-af26c15db171
      features:
        - NVMe 1.4
        - PCIe Gen4 x4
        - Power Management (PM)
        - MSI/MSI-X
